name: Polaris GitHub Action 

# example workflow for Polaris scans using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
  
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: enflo/curl-action@master
      with:
        curl:   curl --location --request GET "https://cdev.altair.synopsys.com/api/portfolio/portfolios" \
        --header 'Accept: application/vnd.synopsys.pm.portfolio-1+json' \
        --header 'Api-token: {secrets.POLARIS_ACCESS_TOKEN}'
  
build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Polaris Scan
        uses: synopsys-sig/synopsys-action@v1.13.0
        with:
          ### SCANNING: Required fields
          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SAST"
          
          ### SCANNING: Optional fields
          polaris_application_name: GitHub Integrations
          polaris_project_name: ${{ github.event.repository.name }}
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # polaris_prComment_enabled: true 
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled
