name: Polaris GitHub Action 

# example workflow for Polaris scans using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Polaris Scan
        uses: synopsys-sig/synopsys-action@v1.13.0
        with:
          ### SCANNING: Required fields
          polaris_server_url: "https://cdev.altair.synopsys.com/api/portfolio/portfolios"
          polaris_access_token: ${{ secrets.POLARIS_TOKEN_CRUDU }}
          polaris_assessment_types: "SAST"
          
          ### SCANNING: Optional fields
          polaris_application_name: "polaris-github-action-webgoat"
          polaris_project_name: ${{ github.event.repository.name }}
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          # polaris_prComment_enabled: true 
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled
